// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_imagesiezechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_imagesiezechange));
        
        string IMigrationMetadata.Id
        {
            get { return "202112311348556_mig_imagesiezechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
